# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy pull request

on:
  pull_request:
    branches: [ "**" ]

env:
  VITE_BASE_PATH: /ProjectZomboidCharacterPlanner/${{ github.event.pull_request.node_id }}/

jobs:
  build:
    name: Build, Lint and Test branch
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact

      - name: Deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ./${{ github.event.pull_request.node_id }}

  comment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :rocket: Testing environment available here: https://eastrall.github.io${{ env.VITE_BASE_PATH }}
          comment_tag: testing_environment_url
          mode: recreate
