name: Destroy Testing Environment of a closed pull request

on:
  pull_request:
    branches: [ "**" ]
    types: [closed]

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create empty dist folder
        run: mkdir dist

      - name: Deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ./${{ github.event.pull_request.node_id }}

  comment:
    name: Stroke Testing environment url inside pull request
    runs-on: ubuntu-latest
    needs: destroy
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ~~:rocket: Testing environment available here: https://eastrall.github.io/ProjectZomboidCharacterPlanner/${{ github.event.pull_request.node_id }}/~~
          comment_tag: testing_environment_url
          mode: recreate
