name: Deploy main branch

on:
  push:
    branches: [ "main" ]

env:
  VITE_BASE_PATH: /ProjectZomboidCharacterPlanner/main/

jobs:
  build-lint-test:
    uses: ./.github/workflows/build-lint-test.yml

  coverage-reporter:
    uses: ./.github/workflows/codacy-coverage-reporter.yml
    needs: build-lint-test
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  destroy: # destroy job can be removed after first run
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create empty dist folder
        run: mkdir dist

      - name: Deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ./

  deploy:
    runs-on: ubuntu-latest
    needs: destroy # should be 'build' after the first run
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact

      - name: Deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ./main
