name: Deploy main branch

on:
  push:
    branches: [ "main" ]

jobs:
  build-lint-test:
    uses: ./.github/workflows/build-lint-test.yml
    with:
      VITE_BASE_PATH: /ProjectZomboidCharacterPlanner/main/

  coverage-reporter:
    uses: ./.github/workflows/codacy-coverage-reporter.yml
    needs: build-lint-test
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-lint-test
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact

      - name: Deploy gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ./main
